server:
  port: 8877
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epidemic?serverTimezone=UTC&&useUnicode=true&&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.list